In [1]:
from option_pricers.black import black76_torch
from option_pricers.kirk76 import kirk76_torch
from option_pricers.bachelier import bachelier_torch
import torch

In [16]:


option = {
    'S_0': 488.25,
    'strike': -15.,
    'time_to_expiry': 90/365,
    'implied_vol': 0.232,
    'dividend': 0.0,
    'riskfree_rate': .2,
    'option_sign':-1.,
    'S_02': 514.5,
    'implied2': 0.2175,
    'coor': 0.9665
}

In [17]:
k76 = kirk76_torch(**option)
k76.premium()


tensor([12.4683], grad_fn=<MulBackward0>)

In [18]:
k76.greeks

In [19]:
option = {
    'S_0': 488.25,
    'strike': 400,
    'time_to_expiry': 90/365,
    'implied_vol': 0.232,
    'dividend': 0.0,
    'riskfree_rate': .035,
    'option_sign':-1.,

}

In [3]:
torch.linspace(480, 510, 5)

tensor([480.0000, 487.5000, 495.0000, 502.5000, 510.0000])

In [4]:
bs = black76_torch(**option)

In [5]:
bs.premium()

RuntimeError: a Tensor with 5 elements cannot be converted to Scalar

In [59]:
bs.premium()
bs.derivative

{'underlying': 488.25,
 'strike': 485.0,
 'premium': 19.601482391357422,
 'delta': -0.4465615153312683,
 'gamma': 0.007274709641933441,
 'rho': 0.40582120418548584,
 'vega': -0.05376381427049637,
 'theta': -0.009663221426308155,
 'strike_greek': -0.007323457393795252}

In [53]:
20.630599975585938 - 20.333393096923828

0.2972068786621094

In [ ]:
{'underlying': 488.25,
 'strike': -15.0,
 'premium': 13.066343307495117,
 'delta': -0.7731530666351318,
 'gamma': 0.02071956731379032,
 'rho': 0.1906406581401825,
 'vega': 1.024949073791504,
 'theta': 0.4840008616447449,
 'strike_greek': -0.020247073844075203}

In [123]:
k76.premium()

tensor([-0.1080], grad_fn=<MulBackward0>)

tensor([4.0563], grad_fn=<MulBackward0>)

In [83]:
k76.bs76.derivative

{'underlying': 0.9974463582038879,
 'strike': 1.0,
 'premium': 0.005409257486462593,
 'delta': -0.35899218916893005,
 'gamma': 18.338478088378906,
 'rho': 11.144805908203125,
 'vega': -6.245401382446289,
 'theta': -0.6727756857872009,
 'strike_greek': -18.29164695739746}

In [84]:
s76 = black76_torch(**option)

TypeError: black76_torch.__init__() got an unexpected keyword argument 'S_02'

In [4]:
s76.premium()

7.344722747802734

In [6]:
s76.derivative

{'underlying': 100.0,
 'strike': 100.0,
 'premium': 7.344722747802734,
 'delta': 0.5142683386802673,
 'gamma': 0.019448297098279,
 'rho': -0.44564077258110046,
 'vega': 0.16579413414001465,
 'theta': -0.009134011343121529,
 'strike_greek': -0.01944829523563385}

In [2]:
import numpy as np

np.linspace(90, 110, 100)

array([ 90.        ,  90.2020202 ,  90.4040404 ,  90.60606061,
        90.80808081,  91.01010101,  91.21212121,  91.41414141,
        91.61616162,  91.81818182,  92.02020202,  92.22222222,
        92.42424242,  92.62626263,  92.82828283,  93.03030303,
        93.23232323,  93.43434343,  93.63636364,  93.83838384,
        94.04040404,  94.24242424,  94.44444444,  94.64646465,
        94.84848485,  95.05050505,  95.25252525,  95.45454545,
        95.65656566,  95.85858586,  96.06060606,  96.26262626,
        96.46464646,  96.66666667,  96.86868687,  97.07070707,
        97.27272727,  97.47474747,  97.67676768,  97.87878788,
        98.08080808,  98.28282828,  98.48484848,  98.68686869,
        98.88888889,  99.09090909,  99.29292929,  99.49494949,
        99.6969697 ,  99.8989899 , 100.1010101 , 100.3030303 ,
       100.50505051, 100.70707071, 100.90909091, 101.11111111,
       101.31313131, 101.51515152, 101.71717172, 101.91919192,
       102.12121212, 102.32323232, 102.52525253, 102.72

In [26]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
from sympy import init_printing
init_printing()
def call_price(sigma, S, K, r, t):
    d1 = np.multiply( 1. / sigma * np.divide(1., np.sqrt(t)),
        np.log(S/K) + (r + sigma**2 / 2.) * t  )
    d2 = d1 - sigma * np.sqrt(t)
    C = np.multiply(S, norm.cdf(d1)) - \
        np.multiply(norm.cdf(d2) * K, np.exp(-r * t))
    return C, d1, d2
def put_price(sigma, S, K, r, t):
    d1 = np.multiply( 1. / sigma * np.divide(1., np.sqrt(t)),
        np.log(S/K) + (r + sigma**2 / 2.) * t  )
    d2 = d1 - sigma * np.sqrt(t)
    P = -np.multiply(S, norm.cdf(-d1)) + \
        np.multiply(norm.cdf(-d2) * K, np.exp(-r * t))
    return P
def bachelier(sigma, S, K, r, t):
    d = (S - K) / (sigma * np.sqrt(t))
    C = np.exp(-r * t) * (S - K) * norm.cdf(d) + \
        np.exp(-r * t) * sigma * np.sqrt(t) * norm.pdf(d)
    return C
t = 1 / 12    #  Time to expiration
sigma = 0.20    #  Black Scholes implied volatility
K = 105         #  Strike Price
r = 0.01        #  Risk-free rate
S = np.linspace(90, 110, 5)    # Let our stock price range between $90 and $110
#  Calculate Black Schole call, put price
C_BlackSholes, d1, d2 = call_price(sigma, S, K, r, t)
P_BlackSholes = put_price(sigma, S, K, r, t)
C_bs, d1, d2 = call_price(sigma, S, K, r, t)
C_ba = bachelier(sigma * S, S, K, r, t)

In [27]:
C_bs, C_ba

(array([0.00686997, 0.10057787, 0.67310661, 2.46109954, 5.8066834 ]),
 array([2.94336203e-03, 7.37783432e-02, 6.16325104e-01, 2.41644450e+00,
        5.77584522e+00]))

In [5]:
option = {
    'S_0': 100.,
    'strike': 100.,
    'time_to_expiry': 90/365,
    'implied_vol': 0.232,
    'dividend': 0.0,
    'riskfree_rate': .036,
    'option_sign':1.,

}

bb = bachelier_torch(**option)
bs = black76_torch(**option)

In [6]:
bb.premium(),bs.premium()

(tensor([5.0310], grad_fn=<AddBackward0>), 4.336068153381348)

In [4]:
bb.premium()

tensor([4.1473], grad_fn=<AddBackward0>)

In [16]:
bb.premium(), bs.premium()

(tensor([20.0746], grad_fn=<AddBackward0>), 17.394975662231445)

In [17]:
bb.derivative, bs.derivative

({'underlying': 400.0,
  'strike': 400.0,
  'premium': 20.074554443359375,
  'delta': 0.5754910707473755,
  'gamma': 0.008522061631083488,
  'rho': 0.8385549187660217,
  'vega': 0.06934279203414917,
  'theta': 0.15165013074874878,
  'strike_greek': -0.008522060699760914},
 {'underlying': 400.0,
  'strike': 400.0,
  'premium': 17.394975662231445,
  'delta': 0.521037757396698,
  'gamma': 0.008938840590417385,
  'rho': 0.11635807156562805,
  'vega': 0.056642137467861176,
  'theta': 0.008410647511482239,
  'strike_greek': -0.00893883965909481})

tensor([20.2187], grad_fn=<AddBackward0>)

In [13]:
bb.derivative

{'underlying': 400.25,
 'strike': 400.0,
 'premium': 20.21869659423828,
 'delta': 0.5320048332214355,
 'gamma': 0.008661385625600815,
 'rho': 0.8508574366569519,
 'vega': -0.0003439246502239257,
 'theta': 0.05601505562663078,
 'strike_greek': -0.008586958050727844}

In [7]:
def bachelier(sigma, S, K, r, t):
    d = (S - K) / (sigma * np.sqrt(t))
    C = np.exp(-r * t) * (S - K) * norm.cdf(d) + \
        np.exp(-r * t) * sigma * np.sqrt(t) * norm.pdf(d)
    return C

tensor([488.2500], requires_grad=True)

In [34]:

Phi = torch.distributions.Normal(0,1).cdf
# pPhi = torch.distributions.prob()

dP = (bb.S_0 * torch.exp(bb.r*bb.tte) - bb.K) / torch.sqrt(bb.sigma**2/(2 * bb.r) * (torch.exp(2*bb.r*bb.tte)-1) )



In [18]:
import numpy as np 

In [19]:
d = (bb.S_0  - bb.K) / (bb.sigma * np.sqrt(bb.tte))
C = np.exp(-bb.r * bb.tte) * (bb.S_0 - bb.K) * norm.cdf(d) + \
    np.exp(-r * t) * sigma * np.sqrt(t) * norm.pdf(d)

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [15]:
# torch.distributions.Distribution.log_prob(0, d)

In [ ]:
torch.exp(-bb.r * bb.tte) * (bb.S_0 * torch.exp(bb.r * bb.tte) - bb.K) * Phi(d) + \
    torch.exp(-bb.r * bb.tte) * torch.sqrt(bb.sigma**2/(2*bb.r) * (torch.exp(2*bb.r*bb.tte)-1) ) * torch.distributions.Distribution.log_prob(d).exp()

In [9]:
def bachelier(sigma, S, K, r, t):
    d = (S * np.exp(r*t) - K) / np.sqrt(sigma**2/(2 * r) * (np.exp(2*r*t)-1) )
   
    C = np.exp(-r * t) * (S * np.exp(r * t) - K) * norm.cdf(d) + \
        np.exp(-r * t) * np.sqrt(sigma**2/(2*r) * (np.exp(2*r*t)-1) ) * norm.pdf(d)

    return C

In [16]:
S = 100
K = 100
t =  90/365
sigma =  0.232 * S
r = .035


In [17]:
import numpy as np
from scipy.stats import norm

In [22]:
bachelier(sigma, S, K, r, t), bachelier(sigma, S, K, r, t) - S + np.exp(-r * t) * K 

(5.018648381529781, 4.159347956422195)

In [37]:
option = {
    'S_0': 100.,
    'strike': 100.,
    'time_to_expiry': 90/365,
    'implied_vol': 0.232,
    'dividend': 0.0,
    'riskfree_rate': .00,
    'option_sign':1.,

}

bb = bachelier_torch(**option)
bs = black76_torch(**option)

In [38]:
bb.premium(),bs.premium()

ValueError: Expected value argument (Tensor of shape (1,)) to be within the support (Real()) of the distribution Normal(loc: 0.0, scale: 1.0), but found invalid values:
tensor([nan], grad_fn=<DivBackward0>)

In [8]:
d = (S * np.exp(r*t) - K) / np.sqrt(sigma**2/(2 * r) * (np.exp(2*r*t)-1) )
np.exp(-r * t) * (S * np.exp(r * t) - K) * norm.cdf(d) + \
        np.exp(-r * t) * np.sqrt(sigma**2/(2*r) * (np.exp(2*r*t)-1) ) * norm.pdf(d)

NameError: name 'np' is not defined

In [70]:
norm.pdf(d)

In [69]:
norm.pdf(d)

In [16]:
mean = torch.Tensor([0.0])
std = torch.Tensor([1.0])

dist = torch.distributions.normal.Normal(mean, std)
print((torch.exp(dist.log_prob(torch.Tensor([d])))).item())


NameError: name 'd' is not defined

In [206]:
option = {
    'S_0': 80.,
    'strike': 79.,
    'time_to_expiry': 77.95/365,
    'implied_vol': 0.2905,
    'dividend': 0.0,
    'riskfree_rate': .042,
    'option_sign':1.,

}


In [207]:
bb = bachelier_torch(**option)
bb.premium()

tensor([5.1723], grad_fn=<AddBackward0>)

In [208]:
_X = bb.S_0
_K = bb.K
_t = bb.tte
_r = bb.r # torch.tensor([0.035]) # 
_s = bb.sigma

In [209]:
def bfs_price(_opttyp, _X, _K, _t, _r, _s):
	Phi = torch.distributions.Normal(0,1)
	_d = (_X - _K) / (_s * torch.sqrt(_t))
	if _opttyp == "C":
		return torch.exp(-_r*_t) * (Phi.cdf(_d) * (_X - _K) + torch.exp(Phi.log_prob(_d)) * (_s * torch.sqrt(_t)))
	else:
		return torch.exp(-_r*_t) * (Phi.cdf(-_d) * (_K - _X) + torch.exp(Phi.log_prob(_d)) * (_s * torch.sqrt(_t)))


In [210]:
p = bfs_price('P', _X, _K, _t, _r, _s* _X)
c = bfs_price('C', _X, _K, _t, _r, _s* _X)

In [211]:
gradient = torch.autograd.grad(c, _X, create_graph=True)

In [212]:
delta, = gradient
delta.backward(retain_graph=True)

In [213]:
_X.grad.item()

0.03574444353580475

In [214]:
c.item()

4.760245323181152

In [205]:
c.item()+delta.item()+_X.grad.item()

4.779132321476936

In [179]:
price = c.item()+delta.item()*_X.grad.item()

In [181]:
price

4.213690303393814